# Generated by Django 3.2.3 on 2021-05-25 15:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('extra_name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('weight_info', models.CharField(max_length=100)),
                ('packaging_info', models.CharField(max_length=100)),
                ('packaging_type', models.CharField(choices=[('tin', 'Tin'), ('packet', 'Packet'), ('sachet', 'Sachet')], max_length=100)),
                ('expired_on', models.DateField(null=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
